In [5]:
# import 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import itertools
import csv
import scikitplot as skplt
from sklearn import preprocessing
from sklearn.cluster import KMeans
from pylab import scatter,show,plot
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

from pandas.plotting import parallel_coordinates
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from itertools import cycle
from sklearn.metrics import precision_score,recall_score,accuracy_score
from sklearn.datasets import make_blobs
#from sklearn.cluster import KMean

#from sklearn_extensions.fuzzy_kmeans import KMedians, FuzzyKMeans
from sklearn.svm import SVC


# load dataset
#data = pd.read_csv('/home/kavin/mylife/2018/knn/bigclusters/cat_knn.csv')
#data_labels = pd.read_csv('/home/kavin/mylife/2018/knn/bigclusters/cat_knn_lab.csv')
sam1 = pd.read_csv('cat_sam1.csv')
sam2 = pd.read_csv('cat_sam2.csv')
sam3 = pd.read_csv('cat_sam3.csv')
sam4 = pd.read_csv('cat_sam4.csv')
#csvfile = '/home/kavin/mylife/2018/knn/bigclusters/bigcluslabels.csv'

le = preprocessing.LabelEncoder()

for col in sam1.columns.values:
	if sam1[col].dtypes=='object':
		le.fit(sam1[col])
		sam1[col]=le.transform(sam1[col])

for col in sam2.columns.values:
	if sam2[col].dtypes=='object':
		le.fit(sam2[col])
		sam2[col]=le.transform(sam2[col])

for col in sam3.columns.values:
	if sam3[col].dtypes=='object':
		le.fit(sam3[col])
		sam3[col]=le.transform(sam3[col])

for col in sam4.columns.values:
	if sam4[col].dtypes=='object':
		le.fit(sam4[col])
		sam4[col]=le.transform(sam4[col])


data = [sam1,sam2,sam3,sam4]
data = pd.concat(data)


data = sam1
print(data)
print('kmeans')
kmeans = KMeans(n_clusters=6, random_state=0).fit(data)
class_labels = kmeans.labels_

print(true_labels)
print('KMeans Cluster Centers')
print(kmeans.cluster_centers_)
print(metrics.adjusted_rand_score(true_labels, class_labels)) 
print('kmedians')
kmedians = KMedians(k=15)
kmedians.fit(data)
class_labels2 = kmeans.labels_
print(class_labels2)

print('fuzzy kmeans')
fuzzy_kmeans = FuzzyKMeans(k=4, m=2)
fuzzy_kmeans.fit(data)
class_labels = fuzzy_kmeans.labels_
print('fuzzy kmeans centroids')
print(fuzzy_kmeans.cluster_centers_)

#print(len(data))
#print(len(class_labels))

data2 = data
idx = 5
data2.insert(loc=idx, column = 'Class', value = class_labels) # to insert new column in dataframe


#neigh = KNeighborsClassifier(n_neighbors=3)
clf = SVC(probability=True, kernel = 'poly')
X_train, X_test, y_train, y_test = train_test_split(data, class_labels, test_size=0.50, random_state=42)
#neigh.fit(X_train, np.ravel(y_train))
clf.fit(X_train, np.ravel(y_train))

y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)

print('Total No. of Data',len(data))
print('80% of Training Data',len(X_train))
print('20% of Testing Data',len(X_test))

print('Predicted Output', clf.predict(X_test))

print('Actual Output' , y_test)

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    #print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

# Compute confusion matrix
cnf_matrix = confusion_matrix(y_pred,y_test)
np.set_printoptions(precision=2)

class_names = [1,2,3,4]
# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=class_names,
                      title='Confusion matrix, without normalization')

#Plot normalized confusion matrix
#plt.figure()
#plot_confusion_matrix(cnf_matrix, classes=class_names, normalize=True,
#                      title='Normalized confusion matrix')

plt.show()

target_names = ['class 1', 'class 2','class 3', 'class 4']
graph_cl = [1,2,3,4]
print('SVM Classifier Performance Metrics')
print(classification_report(y_test, y_pred, target_names=target_names))
precision = precision_score(y_test, y_pred, average=None)
#print(precision)
recall = recall_score(y_test, y_pred, average=None)
#rint(recall)
accuracy = accuracy_score(y_test, y_pred)
print('accuracy:',accuracy)

#plt.scatter(graph_cl,precision,c=graph_cl)
#plt.xlabel('Classes')
#plt.ylabel('Precision')
#plt.show()

plt.plot(graph_cl,precision,color='g')
plt.xlabel('Classes')
plt.ylabel('Precision')
plt.title('Fuzzy Kmeans & SVM Precision')
plt.show()

plt.plot(graph_cl,recall,c='orange')
plt.xlabel('Classes')
plt.ylabel('Recall')
plt.title('Fuzzy Kmeans & SVM Recall')
plt.show()

skplt.metrics.plot_precision_recall_curve(y_test, y_prob)
plt.show()


#X_norm = (X_train - X_train.min())/(X_train.max() - X_train.min())
#data_norm = pd.concat([X_norm, y_train], axis=1)

parallel_coordinates(data2, 'Class')
plt.show()



    Feature1  Feature2  Feature3  Feature4  Feature5
0         71         1         0         1         4
1         20         1         1         0         1
2         67         1         1         1         0
3         37         1         0         0         0
4         34         1         1         0         4
..       ...       ...       ...       ...       ...
85        28         0         1         1         4
86        83         1         0         1         0
87        68         1         0         1         4
88         5         1         0         1         3
89        89         1         1         0         4

[90 rows x 5 columns]
kmeans


C:\Users\saura\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\saura\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1440: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


[4 3 4 2 2 5 4 5 4 1 0 2 0 5 1 1 3 5 3 3 3 3 5 5 5 5 1 5 1 2 0 2 4 1 1 3 4
 0 2 1 0 0 0 4 3 5 2 1 5 0 0 4 4 1 1 0 3 1 4 2 3 0 3 1 5 0 2 2 4 4 2 3 1 4
 1 5 5 2 3 2 3 2 4 2 0 3 0 4 1 0]
KMeans Cluster Centers
[[82.          0.66666667  0.53333333  0.6         2.2       ]
 [ 7.5         0.75        0.375       0.5         1.9375    ]
 [38.          0.46666667  0.53333333  0.53333333  2.4       ]
 [23.          0.86666667  0.6         0.73333333  1.86666667]
 [67.          0.66666667  0.33333333  0.93333333  1.73333333]
 [52.5         0.71428571  0.42857143  0.5         1.71428571]]


NameError: name 'metrics' is not defined

In [7]:
pip install sklearn

  Using cached sklearn-0.0.post11.tar.gz (3.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [18 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  
  If the previous advice does not cover your use case, feel 